name: Code Coverage Check

on:
  push:
    branches:
      - '**' 

jobs:
 lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install linting tools
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8 linting
        run: |
          # Fail if any linting errors are found
          flake8 . | tee lint.log

      - name: Save lint log
        if: always()
        run: |
          echo "<lint>" > lint.xml
          sed 's/^/<line>/' lint.log | sed 's/$/<\/line>/' >> lint.xml
          echo "</lint>" >> lint.xml
      
      - name: Upload lint xml
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: lint.xml
